import 'package:flutter_ui_radio/models/user_model.dart';

class Users {
  List<User> data = const [
    User(
      name: 'Benjamin Cabrera',
      address: '271 Brightwater Avenue, Barstow, Montana, 3045',
      phone: '(968) 535-2706',
      email: 'benjamincabrera@gmail.com',
      website: 'benjamincabrera.com',
    ),
    User(
      name: 'Estrada Copeland',
      address: '914 Rutledge Street, Frierson, Louisiana, 8341',
      phone: '(817) 527-3806',
      email: 'eopeland@gmail.com',
      website: 'eopeland.com',
    ),
    User(
      name: 'Palmer Le',
      address: '520 Brighton Court, Bradenville, Wisconsin, 1985',
      phone: '(987) 450-3897',
      email: 'palmerle@gmail.com',
      website: 'palmerle.com',
    ),
    User(
      name: 'Rosemarie Blanchard',
      address: '678 Debevoise Avenue, Foxworth, Mississippi, 1979',
      phone: '(996) 494-3312',
      email: 'rosemarie@gmail.com',
      website: 'rosemarie.com',
    ),
    User(
      name: 'Bean Case',
      address: '642 Middleton Street, Kraemer, South Dakota, 1220',
      phone: '(858) 596-2260',
      email: 'beancase@gmail.com',
      website: 'beancase.com',
    ),
    User(
      name: 'Guy Hines',
      address: '248 Congress Street, Otranto, Washington, 1498',
      phone: '(986) 534-2012',
      email: 'guyhines@gmail.com',
      website: 'guyhines.com',
    ),
    User(
      name: 'Dominique Castaneda',
      address: '844 Kenilworth Place, Helen, Hawaii, 1086',
      phone: '(865) 413-2109',
      email: 'dominique@gmail.com',
      website: 'dominique.com',
    ),
    User(
      name: 'Faye Carlson',
      address: '458 Grand Street, Edgewater, Connecticut, 6946',
      phone: '(897) 448-3988',
      email: 'fayecarlson@gmail.com',
      website: 'fayecarlson.com',
    ),
    User(
      name: 'Duncan Fox',
      address: '866 Durland Place, Thatcher, Marshall Islands, 5024',
      phone: '(822) 539-3762',
      email: 'duncanfox@gmail.com',
      website: 'duncanfox.com',
    ),
    User(
      name: 'Huffman Salinas',
      address:
          '109 Oak Street, Cumberland, Federated States Of Micronesia, 2942',
      phone: '(936) 415-2498',
      email: 'huffman@gmail.com',
      website: 'huffman.com',
    ),
    User(
      name: 'Nichole Yates',
      address: '593 Henry Street, Rodman, Idaho, 3576',
      phone: '(962) 507-3263',
      email: 'nicholeyates@gmail.com',
      website: 'nicholeyates.com',
    ),
    User(
      name: 'Terrell Castillo',
      address: '977 Dahl Court, Beaverdale, Northern Mariana Islands, 2938',
      phone: '(801) 564-2989',
      email: 'terrellcastillo@gmail.com',
      website: 'terrellcastillo.com',
    ),
    User(
      name: 'Trisha Rose',
      address: '345 Sandford Street, Lodoga, Texas, 5657',
      phone: '(931) 514-3649',
      email: 'trisharose@gmail.com',
      website: 'trisharose.com',
    ),
    User(
      name: 'Carrie Lynn',
      address: '151 Alabama Avenue, Independence, Rhode Island, 1662',
      phone: '(850) 527-3373',
      email: 'carrielynn@gmail.com',
      website: 'carrielynn.com',
    ),
    User(
      name: 'Cunningham Conrad',
      address: '945 Kenmore Court, Gilmore, Utah, 6789',
      phone: '(914) 420-3802',
      email: 'cunningham@gmail.com',
      website: 'cunningham.com',
    ),
    User(
      name: 'Hansen Turner',
      address: '659 Kane Place, Marbury, Minnesota, 1033',
      phone: '(919) 470-2578',
      email: 'hansenturner@gmail.com',
      website: 'hansenturner.com',
    ),
    User(
      name: 'Mcgee Robbins',
      address: '825 Conover Street, Ribera, Florida, 2318',
      phone: '(923) 424-2520',
      email: 'mcgeerobbins@gmail.com',
      website: 'mcgeerobbins.com',
    ),
    User(
      name: 'Shelia Little',
      address: '214 Fair Street, Wyano, Maine, 5560',
      phone: '(835) 406-2182',
      email: 'shelialittle@gmail.com',
      website: 'shelialittle.com',
    ),
    User(
      name: 'Cecile Bond',
      address: '862 Emerald Street, Williamson, California, 3754',
      phone: '(877) 556-2878',
      email: 'cecilebond@gmail.com',
      website: 'cecilebond.com',
    ),
    User(
      name: 'Tamara Underwood',
      address: '450 Monument Walk, Sedley, Nevada, 9757',
      phone: '(868) 449-3849',
      email: 'tamara@gmail.com',
      website: 'tamara.com',
    ),
    User(
      name: 'Michael Austin',
      address: '187 Ryerson Street, Falmouth, South Carolina, 6841',
      phone: '(839) 501-3123',
      email: 'michaelaustin@gmail.com',
      website: 'michaelaustin.com',
    ),
    User(
      name: 'Gay Gates',
      address: '573 Lincoln Terrace, Bethpage, Wyoming, 6234',
      phone: '(857) 558-2484',
      email: 'gaygates@gmail.com',
      website: 'gaygates.com',
    ),
    User(
      name: 'Bridges Acevedo',
      address: '231 Bay Avenue, Vincent, Palau, 4916',
      phone: '(886) 497-3435',
      email: 'acevedo@gmail.com',
      website: 'acevedo.com',
    ),
    User(
      name: 'Glenna Henson',
      address: '537 Bowery Street, Columbus, Alabama, 6408',
      phone: '(872) 444-3372',
      email: 'glennahenson@gmail.com',
      website: 'glennahenson.com',
    ),
    User(
      name: 'Haley Mcleod',
      address: '420 Williamsburg Street, Stollings, Maryland, 1490',
      phone: '(999) 424-3574',
      email: 'haleymcleod@gmail.com',
      website: 'haleymcleod.com',
    )
  ];
}
